// <auto-generated />
namespace GigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedGigIdtoNotificationmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedGigIdtoNotificationmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201607241729270_Added GigId to Notification model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
